# Get all developers from db
# GET http://localhost/uw%20simulation/uw-simulation/api/user.php

# Get a particular user from email
# GET http://localhost/uw%20simulation/uw-simulation/api/user.php?email=hanif.dev@gmail.com

# Add a developer to the database
# POST http://localhost/uw%20simulation/uw-simulation/api/user.php
# Content-Type: application/json;

# {
#     "name": "Yusuf Yusuf",
#     "email": "yusf.dev@gmail.com",
#     "password": "yusuf_1@2",
#     "company": "Utility Ware"
# }

  

#Update user
# GET  http://localhost/uw%20simulation/uw-simulation/api/user.php?edit=hanif.adedotun@gmail.com&field=password&value=hanif_12

#Delete user
# GET http://localhost/uw%20simulation/uw-simulation/api/user.php?delete=second.dev@gmail.com

# Verify user
# GET http://localhost/uw%20simulation/uw-simulation/api/user.php?verify=hanif.dev@gmail.com&pass=hanif_12


# Applications table Methods

# Get all applications
# GET http://localhost/uw%20simulation/uw-simulation/api/app.php

# GET Version of PHP
# GET http://localhost/uw%20simulation/uw-simulation/api/app.php?version

# Add a new application
# POST  http://localhost/uw%20simulation/uw-simulation/api/app.php
# Content-Type: application/json;

# {
#     "email" : "sovam.dev@gmail.com",
#     "name" : "First Application",
#     "size": "5mb",
#     "version": "1.0.3",
#     "compatibility": "Android 6+",
#     "downloads": "116112488",
#     "status": "Published",
#     "age group": "12+",
#     "date of release": "2021-05-25",
#     "logo": "FlyerMaker_11022020_094913.png"
# }

# GET http://localhost/uw%20simulation/uw-simulation/api/app.php?logo


