# Get all developers from db
# GET http://localhost/uw%20simulation/uw-simulation/api/user.php

# Get a particular user from email
# GET http://localhost/uw%20simulation/uw-simulation/api/user.php?email=hanif.dev@gmail.com

# Add a developer to the database
# POST http://localhost/uw%20simulation/uw-simulation/api/user.php
# Content-Type: application/json;

# {
#     "name": "Hanif Adedotun",
#     "email": "hanif.dev@gmail.com",
#     "password": "hanif_12",
#     "company": "Utility Ware"
# }

  

#Update user
# GET  http://localhost/uw%20simulation/uw-simulation/api/user.php?edit=hanif.adedotun@gmail.com&field=password&value=hanif_12

#Delete user
# GET http://localhost/uw%20simulation/uw-simulation/api/user.php?delete=second.dev@gmail.com

# Verify user
# GET http://localhost/uw%20simulation/uw-simulation/api/user.php?verify=hanif.dev@gmail.com&pass=hanif_12
